spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: m4ri4db

  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: fdjkasljfkdlasjkfljdkajfkdlasjkfljkasljfkldjsakljfkdlasjfklsljfkldasjklfjdkasljfkldasjkl
  jwtExpirationInMs: 18000000